[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[window]
dimensions.columns = 75
dimensions.lines = 10

# M Pro 14 inch 2021
# 3024 x 1964
position.x = 1248
position.y = 1033

dynamic_padding = true
padding.x = 10
padding.y = 10

decorations = "Buttonless"
opacity = 0.9
blur = true

option_as_alt = "Both"
decorations_theme_variant = "None"

[scrolling]
history = 10000

[font]
size = 14
normal.family = "FiraCode Nerd Font Mono"
normal.style = "Regular"

[cursor]
style.shape = "Block"
style.blinking = "Never"

[mouse]
hide_when_typing = true

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = false

[selection]
save_to_clipboard = false

[general]
import = ["~/.config/alacritty/themes/tokyonight_night.toml"]
live_config_reload = true
ipc_socket = false

[terminal]
